"use client";
import { useState } from "react";
import { shuffle } from "@/lib/game-engine";
import type { GameProps } from "./GameTypes";
import { CompletionCard } from "./CompletionCard";
export function MatchingGame({activity,onComplete}:GameProps){const[left,setLeft]=useState(()=>shuffle(activity.items));const[right,setRight]=useState(()=>shuffle(activity.items));const[selectedLeft,setSelectedLeft]=useState<string|null>(null);const[selectedRight,setSelectedRight]=useState<string|null>(null);const[matched,setMatched]=useState<string[]>([]);const[attempts,setAttempts]=useState(0);const[feedback,setFeedback]=useState<"correct"|"wrong"|null>(null);const[finished,setFinished]=useState(false);
function evaluate(l:string|null,r:string|null){if(!l||!r)return;const nextAttempts=attempts+1;setAttempts(nextAttempts);if(l===r){const nextMatched=[...matched,l];setMatched(nextMatched);setFeedback("correct");setTimeout(()=>{setSelectedLeft(null);setSelectedRight(null);setFeedback(null)},300);if(nextMatched.length===activity.items.length){const score=Math.max(200,activity.items.length*120-(nextAttempts-activity.items.length)*40);setTimeout(()=>{setFinished(true);onComplete(score,activity.items.length,nextAttempts)},400)}}else{setFeedback("wrong");setTimeout(()=>{setSelectedLeft(null);setSelectedRight(null);setFeedback(null)},550)}}
function replay(){setLeft(shuffle(activity.items));setRight(shuffle(activity.items));setSelectedLeft(null);setSelectedRight(null);setMatched([]);setAttempts(0);setFeedback(null);setFinished(false)} if(finished)return <CompletionCard score={Math.max(200,activity.items.length*120-(attempts-activity.items.length)*40)} correct={activity.items.length} total={attempts} onReplay={replay}/>;
return <div className="game-stage"><div className="game-progress-label"><span>Connect each English phrase to its meaning</span><span>{matched.length}/{activity.items.length} matched</span></div><div className={`matching-board ${feedback?`feedback-${feedback}`:""}`}><div className="matching-column"><small>ENGLISH</small>{left.map(item=><button key={item.id} disabled={matched.includes(item.id)} onClick={()=>{setSelectedLeft(item.id);evaluate(item.id,selectedRight)}} className={selectedLeft===item.id?"selected":""}>{item.hint&&<span>{item.hint}</span>}{item.prompt}{matched.includes(item.id)&&<i>✓</i>}</button>)}</div><div className="matching-column"><small>MEANING</small>{right.map(item=><button key={item.id} disabled={matched.includes(item.id)} onClick={()=>{setSelectedRight(item.id);evaluate(selectedLeft,item.id)}} className={selectedRight===item.id?"selected":""}>{item.answer}{matched.includes(item.id)&&<i>✓</i>}</button>)}</div></div></div>}
