"use client";
import { useMemo,useState } from "react";
import { isCorrectAnswer,sentenceAnswer,shuffle } from "@/lib/game-engine";
import type { GameProps } from "./GameTypes";
import { CompletionCard } from "./CompletionCard";
type Token={id:string;text:string};
export function SentenceBuilderGame({activity,onComplete}:GameProps){const questions=useMemo(()=>activity.items.filter(item=>(item.sentenceParts?.length??0)>1),[activity]);const[index,setIndex]=useState(0);const[pool,setPool]=useState<Token[]>(()=>shuffle((questions[0]?.sentenceParts??[]).map((text,i)=>({id:`${i}-${text}`,text}))));const[answer,setAnswer]=useState<Token[]>([]);const[correct,setCorrect]=useState(0);const[score,setScore]=useState(0);const[feedback,setFeedback]=useState<"correct"|"wrong"|null>(null);const[finished,setFinished]=useState(false);const item=questions[index];
if(!item)return <div className="empty-game"><span>🧩</span><h2>This set needs sentence chunks.</h2><p>Add chunks such as <b>She | goes to school | every day</b> in the activity editor.</p></div>;
function resetQuestion(nextIndex:number){setAnswer([]);setFeedback(null);setPool(shuffle((questions[nextIndex]?.sentenceParts??[]).map((text,i)=>({id:`${i}-${text}`,text}))))} function check(){if(answer.length!==item.sentenceParts?.length)return;const right=isCorrectAnswer(answer.map(t=>t.text).join(" "),sentenceAnswer(item));setFeedback(right?"correct":"wrong");const nc=correct+(right?1:0),ns=score+(right?120:0);setCorrect(nc);setScore(ns);setTimeout(()=>{if(index===questions.length-1){setFinished(true);onComplete(ns,nc,questions.length)}else{const next=index+1;setIndex(next);resetQuestion(next)}},850)} function replay(){setIndex(0);setCorrect(0);setScore(0);setFinished(false);resetQuestion(0)} if(finished)return <CompletionCard score={score} correct={correct} total={questions.length} onReplay={replay}/>;
return <div className="game-stage builder-stage"><div className="game-progress-label"><span>Sentence {index+1} of {questions.length}</span><span>{score} points</span></div><div className="game-progress"><span style={{width:`${((index+1)/questions.length)*100}%`}}/></div><div className="game-question"><span className="question-icon">🧩</span><small>SENTENCE BUILDER</small><h2>Put the sentence in order</h2>{item.hint&&<p>Hint: {item.hint} {item.answer}</p>}</div><div className={`builder-answer ${feedback?`feedback-${feedback}`:""}`}>{answer.length===0&&<span className="builder-placeholder">Choose the chunks below…</span>}{answer.map(token=><button key={token.id} onClick={()=>{setAnswer(c=>c.filter(t=>t.id!==token.id));setPool(c=>[...c,token])}}>{token.text}</button>)}</div><div className="builder-pool">{pool.map(token=><button key={token.id} onClick={()=>{setPool(c=>c.filter(t=>t.id!==token.id));setAnswer(c=>[...c,token])}}>{token.text}</button>)}</div>{feedback&&<div className={`feedback-message ${feedback}`}>{feedback==="correct"?"✓ Excellent!":`Not quite — ${sentenceAnswer(item)}`}</div>}<button className="button button-primary button-large builder-check" disabled={answer.length!==item.sentenceParts?.length||!!feedback} onClick={check}>Check answer</button></div>}
