"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { saveActivity } from "@/lib/storage";
import type { ActivityItem, ActivityKind, GameType } from "@/lib/types";

const games: { id: GameType; icon: string; label: string; description: string }[] = [
  { id: "flashcards", icon: "🃏", label: "Flashcards", description: "Reveal prompt and answer" }, { id: "memory", icon: "🧠", label: "Memory", description: "Find matching pairs" }, { id: "matching", icon: "🔗", label: "Matching", description: "Connect prompts and answers" }, { id: "sentence-builder", icon: "🧩", label: "Sentence Builder", description: "Put chunks in order" }, { id: "gap-fill", icon: "✏️", label: "Gap Fill", description: "Complete the sentence" }, { id: "quiz", icon: "🏆", label: "Quiz", description: "Quick multiple choice" },
];
const emptyItem = (index: number): ActivityItem => ({ id: `item-${Date.now()}-${index}`, prompt: "", answer: "", hint: "", example: "", gapSentence: "", distractors: [], sentenceParts: [] });

export function ActivityEditor() {
  const router = useRouter(); const [title,setTitle]=useState(""); const [description,setDescription]=useState(""); const [topic,setTopic]=useState(""); const [level,setLevel]=useState("A1–A2"); const [grade,setGrade]=useState("7th grade"); const [kind,setKind]=useState<ActivityKind>("mixed"); const [enabledGames,setEnabledGames]=useState<GameType[]>(games.map(g=>g.id)); const [items,setItems]=useState<ActivityItem[]>([emptyItem(1),emptyItem(2),emptyItem(3),emptyItem(4)]); const [error,setError]=useState("");
  const updateItem=(index:number,patch:Partial<ActivityItem>)=>setItems(current=>current.map((item,i)=>i===index?{...item,...patch}:item));
  const toggleGame=(game:GameType)=>setEnabledGames(current=>current.includes(game)?current.filter(id=>id!==game):[...current,game]);
  function submit(){ const validItems=items.filter(item=>item.prompt.trim()&&item.answer.trim()); if(!title.trim()) return setError("Give your activity a title."); if(validItems.length<2) return setError("Add at least two complete prompt/answer items."); if(!enabledGames.length) return setError("Choose at least one game mode."); const now=new Date().toISOString(); const slug=title.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"activity"; const id=`${slug}-${Date.now().toString(36)}`; saveActivity({id,title:title.trim(),description:description.trim()||"Interactive English classroom activity.",subject:"English",topic:topic.trim()||"English practice",level,grade,kind,items:validItems,enabledGames,createdAt:now,updatedAt:now}); router.push(`/play/${id}`); }
  return <main className="editor-main"><section className="editor-heading"><div><span className="eyebrow">Activity builder</span><h1>Create once. Play many ways.</h1><p>Start with the language. ClassPlay turns it into different classroom interactions.</p></div><button className="button button-primary button-large" onClick={submit}>Save & play →</button></section>{error&&<div className="alert-error">{error}</div>}<div className="editor-layout">
    <section className="editor-panel"><div className="panel-heading"><span>1</span><div><h2>Activity details</h2><p>Help yourself find this set later.</p></div></div><div className="form-grid"><label className="field field-wide"><span>Title</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Present Simple — Daily Routine" /></label><label className="field field-wide"><span>Description</span><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="What will students practise?" rows={2}/></label><label className="field"><span>Topic</span><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Present Simple" /></label><label className="field"><span>Level</span><select value={level} onChange={e=>setLevel(e.target.value)}><option>A1</option><option>A1–A2</option><option>A2</option><option>A2–B1</option><option>B1</option><option>B1–B2</option></select></label><label className="field"><span>Grade</span><select value={grade} onChange={e=>setGrade(e.target.value)}><option>6th grade</option><option>7th grade</option><option>8th grade</option><option>9th grade</option><option>Private class</option></select></label><label className="field"><span>Content type</span><select value={kind} onChange={e=>setKind(e.target.value as ActivityKind)}><option value="mixed">Mixed</option><option value="vocabulary">Vocabulary</option><option value="grammar">Grammar</option></select></label></div></section>
    <section className="editor-panel"><div className="panel-heading"><span>2</span><div><h2>Choose game modes</h2><p>You can reuse the same content across all of them.</p></div></div><div className="game-picker-grid">{games.map(game=><button key={game.id} className={`game-picker ${enabledGames.includes(game.id)?"selected":""}`} onClick={()=>toggleGame(game.id)}><b>{game.icon}</b><span><strong>{game.label}</strong><small>{game.description}</small></span><i>{enabledGames.includes(game.id)?"✓":"+"}</i></button>)}</div></section>
    <section className="editor-panel"><div className="panel-heading"><span>3</span><div><h2>Add your language</h2><p>Prompt + answer power the core games. Extra fields unlock grammar practice.</p></div></div><div className="item-list">{items.map((item,index)=><article className="item-editor" key={item.id}><div className="item-number">{index+1}</div><div className="item-editor-grid"><label className="field"><span>Prompt / English</span><input value={item.prompt} onChange={e=>updateItem(index,{prompt:e.target.value})} placeholder="wake up" /></label><label className="field"><span>Answer / Meaning</span><input value={item.answer} onChange={e=>updateItem(index,{answer:e.target.value})} placeholder="acordar" /></label><label className="field"><span>Visual hint</span><input value={item.hint??""} onChange={e=>updateItem(index,{hint:e.target.value})} placeholder="🌅 or short clue" /></label><label className="field field-wide"><span>Example sentence</span><input value={item.example??""} onChange={e=>updateItem(index,{example:e.target.value})} placeholder="She wakes up at 6:30 every day." /></label><label className="field field-wide"><span>Gap sentence</span><input value={item.gapSentence??""} onChange={e=>updateItem(index,{gapSentence:e.target.value})} placeholder="She _____ at 6:30 every day." /></label><label className="field field-wide"><span>Sentence chunks <em>(separate with |)</em></span><input value={(item.sentenceParts??[]).join(" | ")} onChange={e=>updateItem(index,{sentenceParts:e.target.value.split("|").map(p=>p.trim()).filter(Boolean)})} placeholder="She | wakes up | at 6:30 | every day" /></label><label className="field field-wide"><span>Gap distractors <em>(separate with |)</em></span><input value={(item.distractors??[]).join(" | ")} onChange={e=>updateItem(index,{distractors:e.target.value.split("|").map(p=>p.trim()).filter(Boolean)})} placeholder="wake up | waking up | woke up" /></label></div>{items.length>2&&<button className="remove-item" onClick={()=>setItems(current=>current.filter((_,i)=>i!==index))}>×</button>}</article>)}</div><button className="button button-soft add-item-button" onClick={()=>setItems(current=>[...current,emptyItem(current.length+1)])}>+ Add another item</button></section>
  </div></main>;
}
