"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { addGameResult,getActivity } from "@/lib/storage";
import type { ActivitySet,GameType } from "@/lib/types";
import { FlashcardsGame } from "./games/FlashcardsGame";import { MemoryGame } from "./games/MemoryGame";import { MatchingGame } from "./games/MatchingGame";import { SentenceBuilderGame } from "./games/SentenceBuilderGame";import { GapFillGame } from "./games/GapFillGame";import { QuizGame } from "./games/QuizGame";
const gameInfo:Record<GameType,{icon:string;name:string;description:string;className:string}>={flashcards:{icon:"🃏",name:"Flashcards",description:"Reveal, remember and self-check",className:"mint"},memory:{icon:"🧠",name:"Memory",description:"Find matching pairs",className:"violet"},matching:{icon:"🔗",name:"Matching",description:"Connect English and meaning",className:"blue"},"sentence-builder":{icon:"🧩",name:"Sentence Builder",description:"Put chunks in the right order",className:"orange"},"gap-fill":{icon:"✏️",name:"Gap Fill",description:"Complete the missing language",className:"pink"},quiz:{icon:"🏆",name:"Quiz",description:"Fast multiple-choice challenge",className:"yellow"}};
export function GameHub({activityId}:{activityId:string}){const[activity,setActivity]=useState<ActivitySet|null>(null);const[mode,setMode]=useState<GameType|null>(null);const[missing,setMissing]=useState(false);useEffect(()=>{const loaded=getActivity(activityId);if(!loaded)setMissing(true);else setActivity(loaded)},[activityId]);if(missing)return <main className="not-found"><span>🔎</span><h1>Activity not found</h1><p>This activity may have been deleted or was created in another browser.</p><Link className="button button-primary" href="/dashboard">Back to library</Link></main>;if(!activity)return <main className="loading-screen">Loading ClassPlay…</main>;function complete(game:GameType,score:number,correct:number,total:number){addGameResult({game,activityId:activity!.id,score,correct,total,completedAt:new Date().toISOString()})}
if(mode){const common={activity,onComplete:(score:number,correct:number,total:number)=>complete(mode,score,correct,total)};return <main className="play-screen"><header className="play-header"><button className="play-brand" onClick={()=>setMode(null)}><b>C</b><span>ClassPlay</span></button><div className="play-title"><small>{activity.topic}</small><strong>{activity.title}</strong></div><button className="button button-soft button-small" onClick={()=>setMode(null)}>← Game modes</button></header><section className="play-canvas">{mode==="flashcards"&&<FlashcardsGame {...common}/>} {mode==="memory"&&<MemoryGame {...common}/>} {mode==="matching"&&<MatchingGame {...common}/>} {mode==="sentence-builder"&&<SentenceBuilderGame {...common}/>} {mode==="gap-fill"&&<GapFillGame {...common}/>} {mode==="quiz"&&<QuizGame {...common}/>}</section></main>}
return <main className="mode-screen"><header className="mode-header"><Link className="play-brand" href="/dashboard"><b>C</b><span>ClassPlay</span></Link><Link href="/dashboard" className="button button-soft button-small">← Library</Link></header><section className="mode-hero"><span className="eyebrow">Ready to play</span><h1>{activity.title}</h1><p>{activity.description}</p><div className="mode-meta"><span>{activity.grade}</span><span>{activity.level}</span><span>{activity.items.length} items</span></div></section><section className="mode-picker"><div className="mode-picker-heading"><div><small>CHOOSE A MODE</small><h2>How do you want to practise?</h2></div><span>{activity.enabledGames.length} games available</span></div><div className="mode-grid">{activity.enabledGames.map(game=>{const info=gameInfo[game];return <button key={game} className={`mode-card ${info.className}`} onClick={()=>setMode(game)}><span className="mode-icon">{info.icon}</span><span><strong>{info.name}</strong><small>{info.description}</small></span><i>→</i></button>})}</div></section></main>}
